# Code example from Context Engineering with Elasticsearch book
# Copyright 2026 by Enrico Zimuel. All rights reserved.

import json
import os
import requests

from openai import OpenAI
from urllib.parse import quote

OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5-nano-2025-08-07")
# Make sure to have OPENAI_API_KEY set in your environment variables
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

def get_weather(location: str) -> str:
    # Request to a weather API to get the latitude and longitude of the location
    # using https://geocoding-api.open-meteo.com
    geolocation_url = f"https://geocoding-api.open-meteo.com/v1/search?name={quote(location)}&count=1"
    response = requests.get(geolocation_url)
    if response.status_code != 200:
        raise Exception(f"Error fetching geocoding data: {response.status_code} - {response.text}")
    
    geocodingData = response.json()
    if not geocodingData.get("results") or not geocodingData["results"]:
        raise Exception(f"Location '{location}' not found")
    
    latitude = geocodingData["results"][0]["latitude"]
    longitude = geocodingData["results"][0]["longitude"]
    name = geocodingData["results"][0]["name"]

    # Retrieve the weather information using the geolocation from the previous request
    # using https://api.open-meteo.com
    weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current=temperature_2m,apparent_temperature,relative_humidity_2m,wind_speed_10m,wind_gusts_10m,weather_code"
    response = requests.get(weather_url)
    if response.status_code != 200:
        raise Exception(f"Error fetching weather data: {response.status_code} - {response.text}")
    
    data = response.json()
    return {
        "temperature": data["current"]["temperature_2m"],
        "feelsLike": data["current"]["apparent_temperature"],
        "humidity": data["current"]["relative_humidity_2m"],
        "windSpeed": data["current"]["wind_speed_10m"],
        "windGust": data["current"]["wind_gusts_10m"],
        "conditions": get_weather_condition(data["current"]["weather_code"]),
        "location": name,
    }

def get_weather_condition(code: int) -> str:
    conditions = {
        0: "Clear sky",
        1: "Mainly clear",
        2: "Partly cloudy",
        3: "Overcast",
        45: "Foggy",
        48: "Depositing rime fog",
        51: "Light drizzle",
        53: "Moderate drizzle",
        55: "Dense drizzle",
        56: "Light freezing drizzle",
        57: "Dense freezing drizzle",
        61: "Slight rain",
        63: "Moderate rain",
        65: "Heavy rain",
        66: "Light freezing rain",
        67: "Heavy freezing rain",
        71: "Slight snow fall",
        73: "Moderate snow fall",
        75: "Heavy snow fall",
        77: "Snow grains",
        80: "Slight rain showers",
        81: "Moderate rain showers",
        82: "Violent rain showers",
        85: "Slight snow showers",
        86: "Heavy snow showers",
        95: "Thunderstorm",
        96: "Thunderstorm with slight hail",
        99: "Thunderstorm with heavy hail",
    }
    return conditions.get(code, "Unknown")

llm = OpenAI(api_key=OPENAI_API_KEY)
tools = [
    {
        "type": "function",
        "name": "get_weather",
        "description": "Get current temperature for a given location.",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "City and country e.g. Rome, Italy"
                }
            },
            "required": ["location"]
        }
    }
]
messages = [
    { "role": "user", "content": "What's the temperate now in Milan?" }
]
print("User's question:")
print(messages[0]["content"])

# The response will contain a tool_calls field with the function name and arguments to call
response = llm.responses.create(
    model=OPENAI_MODEL,
    input=messages,
    tools=tools
)

# Save function call outputs for subsequent requests
messages += response.output

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_weather":
            kwargs = json.loads(item.arguments)
            print(f"- Calling tool 'get_weather' with arguments: {kwargs}")
            weather = get_weather(**kwargs)

            # Provide function call results to the model
            messages.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({
                  "weather": weather
                })
            })

final_response = llm.responses.create(
    model=OPENAI_MODEL,
    instructions="Respond only with a weather report generated by a tool.",
    input=messages,
    tools=tools,
)
print("Answer from LLM:")
print(final_response.output_text)